### ISSUE TITLE
Uses of type variable (`_Ptr<T>`) inside generic function not reverted to `void*`

### ISSUE THREAD

**Issue by john-h-kastner** [correctcomputation/C3#11]
For example
```c
_Itype_for_any(T) void test(void * p : itype(_Ptr<T>)) {
  _Ptr<T> tmp = p;
}
```
reverts to
```c
void test(void * p ) {
  T * tmp = p;
}
```

This reversion would require something more than the current parsing approach since type variables can use arbitrary names, and these names could just as easily refer to a typedef.

**Comment by mwhicks1** [comment]
That's an interesting one. Here's a thought:

When the parser sees `_Itype_for_any(T)` it should create set a global list (ref) of type variables to be `["T"]`. Or, if the list already exists, it can add to it. Then it waits for the first curly brace it sees, and sets a flag; this indicates it's within a function. Now, when processing `_Ptr` etc. in that function, if it turns out that the target type is in the above list, we replace it with `void` instead. When we hit the closing curly brace for the function, we reset the list.

Implementing this will be tricky. We need to know:
- When are we in between the curly braces? We can set a global flag that the pointer processing code can check, to know that we are. (See below)
- When we see a closing right curly brace, how do we know if it ends the scope? We probably need to have rules that pair up open and close curly braces, like we have now for parentheses and langle/rangle. And we will need to know when a match is "outermost." For this, we probably can implement a global counter: When you see the first curly brace after the forall, set the count to Some(0). Bump and drop the count with each subsequent curly brace you see. When you reach the rightmost curly brace, if the count is Some(0) after subtracting, then you are done.

**Comment by john-h-kastner** [comment]
Here's an idea for a hack that might work. Just emit `typedef void T;` at the top of the function body. This wouldn't quite be an ideal reversion since this typedef that wasn't in the source will be present, but it seems to work for just getting the reverted code to compile.

**Comment by mwhicks1** [comment]
Fun. That riffs on the idea that we always generalize T. Let me see if I can hack up my fix. If I can't get it to work in 30 minutes, I won't bother.

**Comment by mwhicks1** [comment]
Fixed by https://github.com/correctcomputation/C3/commit/92f2d57a2f0edd2bfea1669ac764a425b211d7ae
