### ISSUE TITLE
Variables with names colliding with  `stdchecked.h` macros 

### ISSUE THREAD

**Issue by john-h-kastner** [correctcomputation/C3#6]
C3 gives a syntax error for variables with names such as `ptr`. 

```c
int ptr;
```
```
At 1:7 syntax error (token ;).
```

The easy fix here is to have a flag to not treat `ptr` as a CheckedC keyword. We could also try to automatically check for the presence of these macros, but that sounds like more effort than its worth.

**Comment by john-h-kastner** [comment]
The easy fix here is to have a flag to not treat `ptr` as a CheckedC keyword.

**Comment by mwhicks1** [comment]
I don't know a good way to address this. The problem is that variables and types are different elements of the C grammar, and the context I'd have to build up to distinguish them would be a pain.

One thought I had was to look for the presence of the `#include <stdchecked.h>` header being included. If it was not, then `ptr` is returned as an `ID`. The problem is that `stdchecked.h` might be included by a different header file, or if you are C3-processing a header file, it might be included before the file you are processing.

Maybe an easy thing to do is just provide a flag to `C3` to say how to treat these things? If you see `#include <stdchecked.h>` then the choice is easy. If you don't, you rely on the flag.

**Comment by mwhicks1** [comment]
Note: In the stuff in the C3 tests, I addressed this issue by renaming `ptr` to `ptr_` in the source file. 😀
